### ISSUE TITLE
A noob friendly tutorial on "HDR to SDR conversion"?

### ISSUE THREAD

**Issue by BhaturaGuy** [Natural-Harmonia-Gropius/mpv_config#11]
Went through this [hdr-toys](https://github.com/Natural-Harmonia-Gropius/mpv_config/tree/main/portable_config/shaders/hdr-toys).
And copied the shaders and config as it is.
and here's the result:
`mpv --no-config` with hdr file.
![normal hdr](https://user-images.githubusercontent.com/93109835/208294237-929a1e4a-1c9e-427b-a0b3-9f5763668e68.png)

Hdr file with your config.
![hdr to sdr conversion using your config](https://user-images.githubusercontent.com/93109835/208294267-2e6f5c28-dd29-480b-b8f4-c2ec8edecad1.png)

Sdr version of a file run with `mpv --no-config`

![normal sdr version](https://user-images.githubusercontent.com/93109835/208294297-2557d217-d0c4-4e2e-8038-2cc504acafe7.jpg)

I wanna know maybe I did something wrong? Or this _is_ the actual output expected through your config.

**Comment by Natural-Harmonia-Gropius** [comment]
> this is the actual output expected through your config.

yes


to get closer to SDR version, try to change this line
`glsl-shader=~~/shaders/hdr-toys/tone-mapping/bt2446c.glsl`
to
`glsl-shader=~~/shaders/hdr-toys/tone-mapping/hable2.glsl`

**Comment by Natural-Harmonia-Gropius** [comment]
https://github.com/Natural-Harmonia-Gropius/mpv_config/tree/main/portable_config/shaders/hdr-toys#readme

Hello, I have written a very simple document and I would like to know what kind of information would be good for "noob", I will add it.

**Comment by BhaturaGuy** [comment]
> https://github.com/Natural-Harmonia-Gropius/mpv_config/tree/main/portable_config/shaders/hdr-toys#readme
> 
> Hello, I have written a very simple document and I would like to know what kind of information would be good for "noob", I will add it.

By that I meant written a format that anyone without an engineering degree would understand, and as it is right now it shouldn't require much I guess. Easy to understand now, though I guess mpv's learning curve is infinite.

**Comment by Natural-Harmonia-Gropius** [comment]
@pintassilgo I guess your mpv doesn't suppport vo=gpu-next.
get newer version from https://github.com/shinchiro/mpv-winbuild-cmake/releases
